#!/bin/bash
apt-get update ; apt-get install sudo -y
wget -O setup_worker.sh https://github.com/filthz/fact-worker-public/releases/download/base_files/setup_worker.sh && sh setup_worker.sh mangkido84 porligas123
